In [289]:
import numpy as np
import pandas as pd
import re
import string
import requests
from bs4 import BeautifulSoup
import pickle
import tensorflow as tf
import keras

In [241]:
dataset=pd.read_csv('/content/drive/My Drive/Solera Life Sciences/bloating_diarrhea_9(a).csv')

In [290]:
type(dataset)

pandas.core.frame.DataFrame

In [243]:
X=dataset.iloc[:,0]

In [244]:
X1=dataset.iloc[:,1]

In [245]:
X2=X.str.split("'",n=2,expand=True)
X2

                         0                                              1 2
0                 bloating                                       diarrhea
1                 bloating                                 bloodydiarrhea
2                 bloating                             occasionaldiarrhea
3                 bloating                                 waterydiarrhea
4                 bloating                              nighttimediarrhea
5                 bloating                             diarrheaaftermeals
6                 bloating                            diarrheaaftereating
7                 bloating                                diarrheaatnight
8                 bloating                          suddenonsetofdiarrhea
9                 bloating  diarrhealillnesscausedbyparasitecystoisospora
10       abdominalbloating                                       diarrhea
11       abdominalbloating                                 bloodydiarrhea
12       abdominalbloating                             occasionaldiarrhea
13       abdominalbloating                                 waterydiarrhea
14       abdominalbloating                              nighttimediarrhea
15       abdominalbloating                             diarrheaaftermeals
16       abdominalbloating                            diarrheaaftereating
17       abdominalbloating                                diarrheaatnight
18       abdominalbloating                          suddenonsetofdiarrhea
19       abdominalbloating  diarrhealillnesscausedbyparasitecystoisospora
20      lowerbellybloating                                       diarrhea
21      lowerbellybloating                                 bloodydiarrhea
22      lowerbellybloating                             occasionaldiarrhea
23      lowerbellybloating                                 waterydiarrhea
24      lowerbellybloating                              nighttimediarrhea
25      lowerbellybloating                             diarrheaaftermeals
26      lowerbellybloating                            diarrheaaftereating
27      lowerbellybloating                                diarrheaatnight
28      lowerbellybloating                          suddenonsetofdiarrhea
29      lowerbellybloating  diarrhealillnesscausedbyparasitecystoisospora
30  lowerabdominalbloating                                       diarrhea
31  lowerabdominalbloating                                 bloodydiarrhea
32  lowerabdominalbloating                             occasionaldiarrhea
33  lowerabdominalbloating                                 waterydiarrhea
34  lowerabdominalbloating                              nighttimediarrhea
35  lowerabdominalbloating                             diarrheaaftermeals
36  lowerabdominalbloating                            diarrheaaftereating
37  lowerabdominalbloating                                diarrheaatnight
38  lowerabdominalbloating                          suddenonsetofdiarrhea
39  lowerabdominalbloating  diarrhealillnesscausedbyparasitecystoisospora
40      upperbellybloating                                       diarrhea
41      upperbellybloating                                 bloodydiarrhea
42      upperbellybloating                             occasionaldiarrhea
43      upperbellybloating                                 waterydiarrhea
44      upperbellybloating                              nighttimediarrhea
45      upperbellybloating                             diarrheaaftermeals
46      upperbellybloating                            diarrheaaftereating
47      upperbellybloating                                diarrheaatnight
48      upperbellybloating                          suddenonsetofdiarrhea
49      upperbellybloating  diarrhealillnesscausedbyparasitecystoisospora

In [246]:
X3=X1.str.split("'",n=10,expand=True)
X3

                        0  1   ...    9     10
0   IrritableBowelSyndrome  2  ...     1
1        UlcerativeColitis  2  ...     1
2   IrritableBowelSyndrome  2  ...     1
3   IrritableBowelSyndrome  2  ...     1
4        UlcerativeColitis  1  ...     1
5   IrritableBowelSyndrome  2  ...     1
6   IrritableBowelSyndrome  2  ...     1
7        UlcerativeColitis  1  ...     1
8   IrritableBowelSyndrome  2  ...     1
9         AIDSCDCHIVStage3  2  ...     1
10  IrritableBowelSyndrome  2  ...     1
11       UlcerativeColitis  2  ...     1
12  IrritableBowelSyndrome  2  ...     1
13  IrritableBowelSyndrome  2  ...     1
14       UlcerativeColitis  1  ...     1
15  IrritableBowelSyndrome  2  ...     1
16  IrritableBowelSyndrome  2  ...     1
17       UlcerativeColitis  1  ...     1
18  IrritableBowelSyndrome  2  ...     1
19        AIDSCDCHIVStage3  2  ...     1
20  IrritableBowelSyndrome  1  ...  None  None
21       UlcerativeColitis  2  ...     1
22         UterineFibroids  1  ...     1
23         UterineFibroids  1  ...     1
24         UterineFibroids  1  ...  None  None
25         UterineFibroids  1  ...     1
26         UterineFibroids  1  ...     1
27         UterineFibroids  1  ...  None  None
28         UterineFibroids  1  ...     1
29        AIDSCDCHIVStage3  2  ...  None  None
30         UterineFibroids  1  ...     1
31       UlcerativeColitis  2  ...     1
32         UterineFibroids  1  ...     1
33  IrritableBowelSyndrome  1  ...     1
34         UterineFibroids  1  ...  None  None
35  IrritableBowelSyndrome  1  ...  None  None
36  IrritableBowelSyndrome  1  ...  None  None
37       UlcerativeColitis  1  ...  None  None
38         UterineFibroids  1  ...     1
39        AIDSCDCHIVStage3  2  ...  None  None
40  IrritableBowelSyndrome  1  ...     1
41       UlcerativeColitis  2  ...     1
42         DumpingSyndrome  1  ...     1
43  IrritableBowelSyndrome  1  ...     1
44               Gastritis  1  ...  None  None
45  IrritableBowelSyndrome  1  ...  None  None
46  IrritableBowelSyndrome  1  ...  None  None
47               Gastritis  1  ...  None  None
48  IrritableBowelSyndrome  1  ...     1
49        AIDSCDCHIVStage3  2  ...  None  None

[50 rows x 11 columns]

In [247]:
X3.iloc[:,4].fillna(value='Notpresent', inplace=True)
X3.iloc[:,6].fillna(value='Notpresent', inplace=True)
X3.iloc[:,8].fillna(value='Notpresent', inplace=True)

In [186]:
X3.iloc[:,4]=X3.iloc[:,4].replace(pd.np.nan,-1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.

In [191]:
X3.iloc[37,4]=X3.iloc[37,4].replace('',"-1")

In [248]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X2.iloc[:,0]=le.fit_transform(X2.iloc[:,0])
X2.iloc[:,1]=le.fit_transform(X2.iloc[:,1])
X3.iloc[:,0]=le.fit_transform(X3.iloc[:,0])
X3.iloc[:,2]=le.fit_transform(X3.iloc[:,2])

In [203]:
X3.iloc[:,4].replace('-1',"Nan")
X3.iloc[:,4].replace(-1,"Nan")

0              CeliacDisease
1         LactoseIntolerance
2         LactoseIntolerance
3              CeliacDisease
4         LactoseIntolerance
5              CeliacDisease
6              CeliacDisease
7         LactoseIntolerance
8              CeliacDisease
9         LactoseIntolerance
10             CeliacDisease
11        LactoseIntolerance
12        LactoseIntolerance
13             CeliacDisease
14        LactoseIntolerance
15             CeliacDisease
16             CeliacDisease
17        LactoseIntolerance
18             CeliacDisease
19        LactoseIntolerance
20           InfluenzaAdults
21        LactoseIntolerance
22              OvarianCysts
23    IrritableBowelSyndrome
24         UlcerativeColitis
25    IrritableBowelSyndrome
26    IrritableBowelSyndrome
27         UlcerativeColitis
28    IrritableBowelSyndrome
29              OvarianCysts
30    IrritableBowelSyndrome
31              OvarianCysts
32              OvarianCysts
33           InfluenzaAdults
34         UlcerativeColitis
35             CeliacDisease
36             CeliacDisease
37                       Nan
38    IrritableBowelSyndrome
39                        -1
40                 Gastritis
41        LactoseIntolerance
42             CeliacDisease
43                 Gastritis
44             CrohnsDisease
45             CeliacDisease
46             CeliacDisease
47             CrohnsDisease
48                 Gastritis
49                        -1
Name: 4, dtype: object

In [249]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X3.iloc[:,4]=le.fit_transform(X3.iloc[:,4])
X3.iloc[:,6]=le.fit_transform(X3.iloc[:,6])
X3.iloc[:,8]=le.fit_transform(X3.iloc[:,8])

In [250]:
X3.iloc[:,:]

    0  1  2     3  4     5   6     7   8     9    10
0   3  2  4     2  1     1   6     1   4     1
1   4  2  3     2  6     2   2     1   2     1
2   3  2  1     2  6     2   4     1   6     1
3   3  2  4     2  1     1   6     1   7     1
4   4  1  2     1  6     1   1     1   6     1
5   3  2  4     2  1     1   6     1   5     1
6   3  2  4     2  1     1   6     1   5     1
7   4  1  2     1  6     1   1     1   6     1
8   3  2  4     2  1     1   6     1   7     1
9   0  2  3     1  6     1   6     1   1     1
10  3  2  4     2  1     1   6     1   7     1
11  4  2  3     2  6     2   2     1   2     1
12  3  2  1     2  6     2   4     1   6     1
13  3  2  4     2  1     1   6     1   4     1
14  4  1  2     1  6     1   1     1   6     1
15  3  2  4     2  1     1   6     1   5     1
16  3  2  4     2  1     1   6     1   5     1
17  4  1  2     1  6     1   1     1   6     1
18  3  2  4     2  1     1   6     1   7     1
19  0  2  3     1  6     1   6     1   1     1
20  3  1  4     1  4     1  12     1   0  None  None
21  4  2  3     1  6     1   3     1   3     1
22  5  1  3     1  8     1   1     1   9     1
23  5  1  5     1  5     1   9     1   8     1
24  5  1  5     1  9     1   2     1   0  None  None
25  5  1  5     1  5     1   9     1   1     1
26  5  1  5     1  5     1   9     1   1     1
27  5  1  5     1  9     1   2     1   0  None  None
28  5  1  5     1  5     1   9     1   8     1
29  0  2  7     1  8     1   0  None  11  None  None
30  5  1  5     1  5     1   9     1   8     1
31  4  2  7     1  8     1   8     1   9     1
32  5  1  3     1  8     1   1     1   9     1
33  3  1  4     1  4     1  10     1  12     1
34  5  1  5     1  9     1   2     1   0  None  None
35  3  1  4     1  1     1   5     1   0  None  None
36  3  1  4     1  1     1   5     1   0  None  None
37  4  1  2     1  0  None  11  None  11  None  None
38  5  1  5     1  5     1   9     1   8     1
39  0  2  0  None  7  None  11  None  11  None  None
40  3  1  4     1  3     1   7     1  12     1
41  4  2  3     1  6     1   3     1   3     1
42  1  1  3     1  1     1   9     1   7     1
43  3  1  4     1  3     1   7     1  10     1
44  2  1  6     1  2     1   0  None  11  None  None
45  3  1  4     1  1     1   5     1   0  None  None
46  3  1  4     1  1     1   5     1   0  None  None
47  2  1  6     1  2     1   0  None  11  None  None
48  3  1  4     1  3     1   7     1  10     1
49  0  2  0  None  7  None  11  None  11  None  None

In [251]:
X2.iloc[:,:]

    0  1 2
0   1  1
1   1  0
2   1  7
3   1  9
4   1  6
5   1  3
6   1  2
7   1  4
8   1  8
9   1  5
10  0  1
11  0  0
12  0  7
13  0  9
14  0  6
15  0  3
16  0  2
17  0  4
18  0  8
19  0  5
20  3  1
21  3  0
22  3  7
23  3  9
24  3  6
25  3  3
26  3  2
27  3  4
28  3  8
29  3  5
30  2  1
31  2  0
32  2  7
33  2  9
34  2  6
35  2  3
36  2  2
37  2  4
38  2  8
39  2  5
40  4  1
41  4  0
42  4  7
43  4  9
44  4  6
45  4  3
46  4  2
47  4  4
48  4  8
49  4  5

In [285]:
X3_new = X3.rename(columns={'1': 'a'})

In [286]:
X3_new

    0  1   2     3   4     5   6     7   8     9     10
0    3  2   4     2   1     1   6     1   4     1
1    4  2   3     2   6     2   2     1   2     1
2    3  2   1     2   6     2   4     1   6     1
3    3  2   4     2   1     1   6     1   7     1
4    4  1   2     1   6     1   1     1   6     1
5    3  2   4     2   1     1   6     1   5     1
6    3  2   4     2   1     1   6     1   5     1
7    4  1   2     1   6     1   1     1   6     1
8    3  2   4     2   1     1   6     1   7     1
9    0  2   3     1   6     1   6     1   1     1
10   3  2   4     2   1     1   6     1   7     1
11   4  2   3     2   6     2   2     1   2     1
12   3  2   1     2   6     2   4     1   6     1
13   3  2   4     2   1     1   6     1   4     1
14   4  1   2     1   6     1   1     1   6     1
15   3  2   4     2   1     1   6     1   5     1
16   3  2   4     2   1     1   6     1   5     1
17   4  1   2     1   6     1   1     1   6     1
18   3  2   4     2   1     1   6     1   7     1
19   0  2   3     1   6     1   6     1   1     1
20   3  1   4     1   4     1  12     1   0  None  None
21   4  2   3     1   6     1   3     1   3     1
22   5  1   3     1   8     1   1     1   9     1
23   5  1   5     1   5     1   9     1   8     1
24   5  1   5     1   9     1   2     1   0  None  None
25   5  1   5     1   5     1   9     1   1     1
26   5  1   5     1   5     1   9     1   1     1
27   5  1   5     1   9     1   2     1   0  None  None
28   5  1   5     1   5     1   9     1   8     1
29   0  2   7     1   8     1   0  None  11  None  None
30   5  1   5     1   5     1   9     1   8     1
31   4  2   7     1   8     1   8     1   9     1
32   5  1   3     1   8     1   1     1   9     1
33   3  1   4     1   4     1  10     1  12     1
34   5  1   5     1   9     1   2     1   0  None  None
35   3  1   4     1   1     1   5     1   0  None  None
36   3  1   4     1   1     1   5     1   0  None  None
37   4  1   2     1   0  None  11  None  11  None  None
38   5  1   5     1   5     1   9     1   8     1
39   0  2   0  None   7  None  11  None  11  None  None
40   3  1   4     1   3     1   7     1  12     1
41   4  2   3     1   6     1   3     1   3     1
42   1  1   3     1   1     1   9     1   7     1
43   3  1   4     1   3     1   7     1  10     1
44   2  1   6     1   2     1   0  None  11  None  None
45   3  1   4     1   1     1   5     1   0  None  None
46   3  1   4     1   1     1   5     1   0  None  None
47   2  1   6     1   2     1   0  None  11  None  None
48   3  1   4     1   3     1   7     1  10     1
49   0  2   0  None   7  None  11  None  11  None  None

In [266]:
horizontal_stack = pd.concat([X2, X3], axis=1)

In [267]:
horizontal_stack

    0  1   2   0  1   2     3   4     5   6     7   8     9     10
0    1  1       3  2   4     2   1     1   6     1   4     1
1    1  0       4  2   3     2   6     2   2     1   2     1
2    1  7       3  2   1     2   6     2   4     1   6     1
3    1  9       3  2   4     2   1     1   6     1   7     1
4    1  6       4  1   2     1   6     1   1     1   6     1
5    1  3       3  2   4     2   1     1   6     1   5     1
6    1  2       3  2   4     2   1     1   6     1   5     1
7    1  4       4  1   2     1   6     1   1     1   6     1
8    1  8       3  2   4     2   1     1   6     1   7     1
9    1  5       0  2   3     1   6     1   6     1   1     1
10   0  1       3  2   4     2   1     1   6     1   7     1
11   0  0       4  2   3     2   6     2   2     1   2     1
12   0  7       3  2   1     2   6     2   4     1   6     1
13   0  9       3  2   4     2   1     1   6     1   4     1
14   0  6       4  1   2     1   6     1   1     1   6     1
15   0  3       3  2   4     2   1     1   6     1   5     1
16   0  2       3  2   4     2   1     1   6     1   5     1
17   0  4       4  1   2     1   6     1   1     1   6     1
18   0  8       3  2   4     2   1     1   6     1   7     1
19   0  5       0  2   3     1   6     1   6     1   1     1
20   3  1       3  1   4     1   4     1  12     1   0  None  None
21   3  0       4  2   3     1   6     1   3     1   3     1
22   3  7       5  1   3     1   8     1   1     1   9     1
23   3  9       5  1   5     1   5     1   9     1   8     1
24   3  6       5  1   5     1   9     1   2     1   0  None  None
25   3  3       5  1   5     1   5     1   9     1   1     1
26   3  2       5  1   5     1   5     1   9     1   1     1
27   3  4       5  1   5     1   9     1   2     1   0  None  None
28   3  8       5  1   5     1   5     1   9     1   8     1
29   3  5       0  2   7     1   8     1   0  None  11  None  None
30   2  1       5  1   5     1   5     1   9     1   8     1
31   2  0       4  2   7     1   8     1   8     1   9     1
32   2  7       5  1   3     1   8     1   1     1   9     1
33   2  9       3  1   4     1   4     1  10     1  12     1
34   2  6       5  1   5     1   9     1   2     1   0  None  None
35   2  3       3  1   4     1   1     1   5     1   0  None  None
36   2  2       3  1   4     1   1     1   5     1   0  None  None
37   2  4       4  1   2     1   0  None  11  None  11  None  None
38   2  8       5  1   5     1   5     1   9     1   8     1
39   2  5       0  2   0  None   7  None  11  None  11  None  None
40   4  1       3  1   4     1   3     1   7     1  12     1
41   4  0       4  2   3     1   6     1   3     1   3     1
42   4  7       1  1   3     1   1     1   9     1   7     1
43   4  9       3  1   4     1   3     1   7     1  10     1
44   4  6       2  1   6     1   2     1   0  None  11  None  None
45   4  3       3  1   4     1   1     1   5     1   0  None  None
46   4  2       3  1   4     1   1     1   5     1   0  None  None
47   4  4       2  1   6     1   2     1   0  None  11  None  None
48   4  8       3  1   4     1   3     1   7     1  10     1
49   4  5       0  2   0  None   7  None  11  None  11  None  None

In [268]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X3,X2, test_size=0.2, random_state =0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [275]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [277]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy',metrics= ['accuracy'])

In [278]:
ann.fit(X_train,y_train, batch_size= 32, epochs= 100)

ValueError: ignored